"""Parse extracted solution markdown into normalized structured markdown artifacts.

This step consumes markdown files generated by `extract_solutions`, sends their
content to the local Ollama structured parser, then writes one structured
markdown output per source PDF into the run's `structured` directory.
"""
from __future__ import annotations

import asyncio
import traceback
from pathlib import Path

from profu_logging.feature_logger import FeatureLogger

from exam_parser.parsers.ollama_structured import scoring_scale_md_to_structured_ollama
from exam_parser.parsers.structured_markdown import serialize_solutions_from_normalized_dict
from exam_parser.pipeline.config import Checkpoint, PipelineConfig, RunDirs
from exam_parser.pipeline.settings import settings

STEP_NAME = "parse_solutions"


async def _process_one(
    pdf: Path,
    vision_dir: Path,
    structured_dir: Path,
    checkpoint: Checkpoint,
    logger: FeatureLogger,
) -> None:
    """Parse one solution markdown file and persist its structured markdown output.

    The function expects a `"{stem}.md"` file under `vision_dir`, where `stem`
    comes from the provided PDF filename. On success it writes the parsed
    `"{stem}.md"` artifact to `structured_dir` and marks the file checkpoint.

    Raises:
        FileNotFoundError: If the expected source markdown is missing.
        Exception: Re-raises any parser or I/O error after logging traceback.
    """
    stem = pdf.stem
    vision_path = vision_dir / f"{stem}.md"
    structured_out = structured_dir / f"{stem}.md"

    if not vision_path.is_file():
        raise FileNotFoundError(
            f"Missing markdown for {pdf.name}; run extract_solutions first. Expected: {vision_path}"
        )

    try:
        md_text = vision_path.read_text(encoding="utf-8")
        data: dict = await asyncio.to_thread(
            scoring_scale_md_to_structured_ollama,
            md_text,
            base_url=settings.ollama_base_url,
            model=settings.ollama_model,
            source_stem=stem,
        )
        md_body = serialize_solutions_from_normalized_dict(data)
        structured_out.write_text(md_body, encoding="utf-8")
        logger.info(f"[{STEP_NAME}] Structured markdown written: {structured_out.name}")
        checkpoint.mark_file_done(STEP_NAME, pdf.name)
    except Exception as exc:
        logger.error(exc, traceback=traceback.format_exc())
        raise


async def run(
    config: PipelineConfig,
    dirs: RunDirs,
    checkpoint: Checkpoint,
    logger: FeatureLogger,
) -> None:
    """Run the parse-solutions step for all pending solution PDFs.

    The step resolves pending PDFs from checkpoint state, skips items missing
    extracted markdown, and processes the rest concurrently through Ollama.
    In dry-run mode it only logs intended actions and performs no writes.
    """
    pdfs = sorted(config.solutions_dir.glob("*.pdf"))
    if not pdfs:
        logger.warning(f"[{STEP_NAME}] No PDFs found in {config.solutions_dir}")
        return

    pending = [p for p in pdfs if not checkpoint.is_file_done(STEP_NAME, p.name)]
    logger.info(
        f"[{STEP_NAME}] {len(pdfs)} PDFs total, {len(pdfs) - len(pending)} already parsed, "
        f"{len(pending)} to process"
    )

    if not pending:
        return

    if config.dry_run:
        for p in pending:
            logger.info(f"[{STEP_NAME}] [DRY RUN] Would parse via Ollama: {p.name}")
        return

    tasks = [
        _process_one(pdf, dirs.solutions_vision, dirs.solutions_structured, checkpoint, logger)
        for pdf in pending
        if (dirs.solutions_vision / f"{pdf.stem}.md").is_file()
    ]
    missing_md = [
        p.name
        for p in pending
        if not (dirs.solutions_vision / f"{p.stem}.md").is_file()
    ]
    if missing_md:
        preview = ", ".join(missing_md[:5])
        extra = f" (+{len(missing_md) - 5} more)" if len(missing_md) > 5 else ""
        logger.warning(
            f"[{STEP_NAME}] Skipping {len(missing_md)} file(s) without markdown: {preview}{extra}"
        )

    if not tasks:
        logger.warning(f"[{STEP_NAME}] No markdown files to parse")
        return

    await asyncio.gather(*tasks)
    checkpoint.mark_step_done(STEP_NAME)
    logger.info(f"[{STEP_NAME}] Step complete")
