#!/usr/bin/env bash
#
# Start Langfuse locally using Docker Compose.
#
# Langfuse is an open-source LLM observability platform that provides
# tracing, monitoring, and evaluation for AI applications.
#
# Usage:
#   ./scripts/start-langfuse.sh           # Start Langfuse
#   ./scripts/start-langfuse.sh stop      # Stop and remove containers
#   ./scripts/start-langfuse.sh restart   # Restart Langfuse
#   ./scripts/start-langfuse.sh logs      # View logs
#   ./scripts/start-langfuse.sh status    # Check status
#
# After starting, Langfuse will be available at:
#   - UI: http://localhost:3000
#   - API: http://localhost:3000/api
#
# Default credentials (first run):
#   - Email: (set up during first visit)
#   - Password: (set up during first visit)
#
# Environment variables (set in .env):
#   LANGFUSE_PUBLIC_KEY=pk-lf-...
#   LANGFUSE_SECRET_KEY=sk-lf-...
#   LANGFUSE_HOST=http://localhost:3000  # for local development

set -euo pipefail

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Langfuse configuration (v3 requires ClickHouse, Redis, MinIO, worker + web)
readonly LANGFUSE_DIR="${PROJECT_ROOT}/.langfuse"
readonly DOCKER_COMPOSE_FILE="${LANGFUSE_DIR}/docker-compose.yml"
readonly LANGFUSE_ENV_FILE="${LANGFUSE_DIR}/.env"
readonly COMPOSE_TEMPLATE="${SCRIPT_DIR}/langfuse/docker-compose.yml"
readonly LANGFUSE_PORT="${LANGFUSE_PORT:-3000}"
readonly POSTGRES_PORT="${POSTGRES_PORT:-5432}"

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $*"
}

log_success() {
    echo -e "${GREEN}✓${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $*"
}

log_error() {
    echo -e "${RED}✗${NC} $*" >&2
}

# Check if Docker is installed and running
check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first:"
        log_error "  https://docs.docker.com/get-docker/"
        exit 1
    fi

    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Please start Docker first."
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first:"
        log_error "  https://docs.docker.com/compose/install/"
        exit 1
    fi
}

# Write .env for Docker Compose (Langfuse v3). Created once; delete to regenerate secrets.
write_langfuse_env() {
    mkdir -p "${LANGFUSE_DIR}"

    if [[ -f "${LANGFUSE_ENV_FILE}" ]]; then
        log_info "Using existing ${LANGFUSE_ENV_FILE}"
        return 0
    fi

    log_info "Creating ${LANGFUSE_ENV_FILE} (local dev defaults; delete this file to regenerate secrets)..."

    local pg_pass ck_pass minio_pass redis_pass
    pg_pass="langfuse_dev_postgres"
    ck_pass="langfuse_dev_clickhouse"
    minio_pass="langfuse_dev_minio_secret"
    redis_pass="langfuse_dev_redis_secret"

    local nextauth_secret salt enc_key
    if command -v openssl &> /dev/null; then
        nextauth_secret="$(openssl rand -hex 32)"
        salt="$(openssl rand -hex 32)"
        enc_key="$(openssl rand -hex 32)"
    else
        log_warning "openssl not found; using fixed dev-only secrets (not for production)"
        nextauth_secret="changeme_nextauth_secret_must_be_32_chars_min_xx"
        salt="changeme_salt_must_be_long_enough_for_langfuse_xx"
        enc_key="0000000000000000000000000000000000000000000000000000000000000000"
    fi

    local lf_port minio_api
    lf_port="${LANGFUSE_PORT:-3000}"
    minio_api="${MINIO_API_PORT:-9090}"

    cat > "${LANGFUSE_ENV_FILE}" <<EOF
# Generated by scripts/start-langfuse.sh — Langfuse v3 local stack
# Delete this file and run start again to regenerate secrets.

LANGFUSE_PORT=${lf_port}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=postgres
POSTGRES_VERSION=17

DATABASE_URL=postgresql://postgres:${pg_pass}@postgres:5432/postgres

CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${ck_pass}
CLICKHOUSE_HTTP_PORT=8123
CLICKHOUSE_NATIVE_PORT=9000
CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
CLICKHOUSE_URL=http://clickhouse:8123
CLICKHOUSE_CLUSTER_ENABLED=false

REDIS_AUTH=${redis_pass}
REDIS_PORT=6379

MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${minio_pass}
MINIO_API_PORT=${minio_api}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT:-9091}

NEXTAUTH_URL=http://localhost:${lf_port}
NEXTAUTH_SECRET=${nextauth_secret}
SALT=${salt}
ENCRYPTION_KEY=${enc_key}

TELEMETRY_ENABLED=${LANGFUSE_TELEMETRY_ENABLED:-true}
LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://localhost:${minio_api}
EOF

    chmod 600 "${LANGFUSE_ENV_FILE}" 2>/dev/null || true
    log_success "Wrote ${LANGFUSE_ENV_FILE}"
}

# Copy v3 docker-compose from repo template; refresh if missing or outdated (no ClickHouse).
setup_langfuse_config() {
    log_info "Setting up Langfuse v3 stack (PostgreSQL, ClickHouse, Redis, MinIO, web + worker)..."

    mkdir -p "${LANGFUSE_DIR}"

    if [[ ! -f "${COMPOSE_TEMPLATE}" ]]; then
        log_error "Missing template: ${COMPOSE_TEMPLATE}"
        exit 1
    fi

    local need_copy="0"
    if [[ ! -f "${DOCKER_COMPOSE_FILE}" ]]; then
        need_copy="1"
    elif ! grep -q "clickhouse:" "${DOCKER_COMPOSE_FILE}" 2>/dev/null; then
        log_warning "Existing ${DOCKER_COMPOSE_FILE} is missing ClickHouse (Langfuse v3). Replacing with v3 template."
        need_copy="1"
    fi

    if [[ "${need_copy}" == "1" ]]; then
        cp -f "${COMPOSE_TEMPLATE}" "${DOCKER_COMPOSE_FILE}"
        log_success "Installed ${DOCKER_COMPOSE_FILE}"
        log_warning "If the old single-container stack left bad volumes, run from ${LANGFUSE_DIR}: docker compose down -v"
    fi

    write_langfuse_env
}

# Create the required S3 bucket in MinIO using the mc client bundled in the MinIO image.
# Langfuse v3 stores event uploads and media in a bucket named 'langfuse' by default.
# This must run after MinIO is healthy; it is idempotent (--ignore-existing).
create_minio_bucket() {
    local bucket="${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}"
    local minio_user="${MINIO_ROOT_USER:-minio}"
    local minio_pass="${MINIO_ROOT_PASSWORD:-}"

    if [[ -z "${minio_pass}" ]]; then
        log_warning "MINIO_ROOT_PASSWORD not set; skipping bucket creation."
        return 0
    fi

    log_info "Ensuring MinIO bucket '${bucket}' exists..."

    if docker exec langfuse-minio mc alias set local "http://localhost:9000" \
            "${minio_user}" "${minio_pass}" --quiet > /dev/null 2>&1 \
       && docker exec langfuse-minio mc mb --ignore-existing "local/${bucket}" > /dev/null 2>&1; then
        log_success "MinIO bucket '${bucket}' is ready."
    else
        log_warning "Could not create MinIO bucket '${bucket}'. Span export may fail until the bucket exists."
        log_warning "Create it manually: docker exec langfuse-minio mc mb local/${bucket}"
    fi
}

# Start Langfuse
start_langfuse() {
    log_info "Starting Langfuse..."
    setup_langfuse_config

    # shellcheck source=/dev/null
    set -a
    source "${LANGFUSE_ENV_FILE}" 2>/dev/null || true
    set +a

    cd "${LANGFUSE_DIR}"
    
    # Use docker compose (v2) if available, otherwise docker-compose (v1)
    if docker compose version &> /dev/null; then
        docker compose up -d
    else
        docker-compose up -d
    fi

    log_success "Langfuse is starting..."
    log_info "Waiting for services to be healthy (v3 stack may take 1–3 minutes on first boot)..."

    # Give MinIO time to become healthy before creating the bucket
    sleep 10
    create_minio_bucket

    local max_attempts=60
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        if curl -sf "http://localhost:${LANGFUSE_PORT}/api/public/health" > /dev/null 2>&1; then
            log_success "Langfuse is ready!"
            # Load ports and passwords written to .env (same values as in write_langfuse_env)
            # shellcheck source=/dev/null
            set -a
            source "${LANGFUSE_ENV_FILE}" 2>/dev/null || true
            set +a
            local _lf_port="${LANGFUSE_PORT:-3000}"
            local _pg_port="${POSTGRES_PORT:-5432}"
            local _minio_api="${MINIO_API_PORT:-9090}"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            log_info "🌐 Langfuse (app):"
            echo "   UI:  ${GREEN}http://localhost:${_lf_port}${NC}"
            echo "   API: ${GREEN}http://localhost:${_lf_port}/api${NC}"
            echo ""
            log_info "📊 PostgreSQL:"
            echo "   Host:     127.0.0.1"
            echo "   Port:     ${_pg_port}"
            echo "   Database: ${POSTGRES_DB:-postgres}"
            echo "   User:     ${POSTGRES_USER:-postgres}"
            echo "   Password: ${POSTGRES_PASSWORD:-see .langfuse/.env}"
            echo ""
            log_info "🧱 ClickHouse (traces / analytics):"
            echo "   HTTP:     http://127.0.0.1:${CLICKHOUSE_HTTP_PORT:-8123}"
            echo "   User:     ${CLICKHOUSE_USER:-clickhouse}"
            echo "   Password: ${CLICKHOUSE_PASSWORD:-see .langfuse/.env}"
            echo ""
            log_info "📦 Redis (queue):"
            echo "   Host:     127.0.0.1"
            echo "   Port:     ${REDIS_PORT:-6379}"
            echo "   Password: ${REDIS_AUTH:-see .langfuse/.env}"
            echo ""
            log_info "🪣 MinIO (S3-compatible uploads):"
            echo "   API:      http://127.0.0.1:${_minio_api}"
            echo "   Console:  http://127.0.0.1:${MINIO_CONSOLE_PORT:-9091}"
            echo "   User:     ${MINIO_ROOT_USER:-minio}"
            echo "   Password: ${MINIO_ROOT_PASSWORD:-see .langfuse/.env}"
            echo ""
            log_info "🔑 Secrets file (full values): ${BLUE}${LANGFUSE_ENV_FILE}${NC}"
            echo ""
            log_warning "⚙️  First-time setup:"
            log_warning "  1. Visit ${BLUE}http://localhost:${_lf_port}${NC}"
            log_warning "  2. Create your first account (any email/password)"
            log_warning "  3. Create a project and copy API keys into your project ${BLUE}.env${NC}:"
            echo ""
            echo "     ${GREEN}LANGFUSE_PUBLIC_KEY${NC}=pk-lf-..."
            echo "     ${GREEN}LANGFUSE_SECRET_KEY${NC}=sk-lf-..."
            echo "     ${GREEN}LANGFUSE_HOST${NC}=http://localhost:${_lf_port}"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            return 0
        fi
        
        attempt=$((attempt + 1))
        sleep 2
    done
    
    log_error "Langfuse did not become healthy within timeout"
    log_error "Check logs with: ./scripts/start-langfuse.sh logs"
    return 1
}

# Stop Langfuse
stop_langfuse() {
    log_info "Stopping Langfuse..."
    
    if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
        log_warning "Langfuse is not configured. Nothing to stop."
        return 0
    fi

    cd "${LANGFUSE_DIR}"
    
    if docker compose version &> /dev/null; then
        docker compose down
    else
        docker-compose down
    fi

    log_success "Langfuse stopped"
}

# Restart Langfuse
restart_langfuse() {
    stop_langfuse
    sleep 2
    start_langfuse
}

# Show logs
show_logs() {
    if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
        log_error "Langfuse is not configured"
        exit 1
    fi

    cd "${LANGFUSE_DIR}"
    
    if docker compose version &> /dev/null; then
        docker compose logs -f --tail=100
    else
        docker-compose logs -f --tail=100
    fi
}

# Show status
show_status() {
    if [ ! -f "${DOCKER_COMPOSE_FILE}" ]; then
        log_warning "Langfuse is not configured"
        return 0
    fi

    if [[ -f "${LANGFUSE_ENV_FILE}" ]]; then
        # shellcheck source=/dev/null
        set -a
        source "${LANGFUSE_ENV_FILE}" 2>/dev/null || true
        set +a
    fi

    cd "${LANGFUSE_DIR}"
    
    echo ""
    log_info "Langfuse containers:"
    echo ""
    
    if docker compose version &> /dev/null; then
        docker compose ps
    else
        docker-compose ps
    fi
    
    echo ""
    
    local _port="${LANGFUSE_PORT:-3000}"
    if curl -sf "http://localhost:${_port}/api/public/health" > /dev/null 2>&1; then
        log_success "Langfuse is healthy and responding at http://localhost:${_port}"
    else
        log_warning "Langfuse is not responding at http://localhost:${_port}"
    fi
    
    echo ""
}

# Main script
main() {
    local command="${1:-start}"
    
    case "${command}" in
        start)
            check_docker
            start_langfuse
            ;;
        stop)
            check_docker
            stop_langfuse
            ;;
        restart)
            check_docker
            restart_langfuse
            ;;
        logs)
            check_docker
            show_logs
            ;;
        status)
            check_docker
            show_status
            ;;
        reconfigure)
            check_docker
            log_info "Replacing compose template and removing ${LANGFUSE_ENV_FILE} (if present)..."
            rm -f "${LANGFUSE_ENV_FILE}"
            rm -f "${DOCKER_COMPOSE_FILE}"
            setup_langfuse_config
            log_success "Run: $0 start"
            ;;
        help|--help|-h)
            cat <<EOF
Usage: $0 [COMMAND]

Commands:
  start        Start Langfuse (default)
  stop         Stop Langfuse containers
  restart      Restart Langfuse
  logs         View Langfuse logs (follow mode)
  status       Show container status and health
  reconfigure  Replace docker-compose.yml from template and regenerate .env (destructive)
  help         Show this help message

Environment variables:
  LANGFUSE_PORT                    Port for Langfuse UI (default: 3000)
  POSTGRES_PORT                    Port for PostgreSQL (default: 5432)
  LANGFUSE_TELEMETRY_ENABLED       Enable telemetry (default: true)
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES  Enable experimental features (default: false)

Examples:
  $0                    # Start Langfuse
  $0 stop               # Stop Langfuse
  $0 logs               # View logs
  LANGFUSE_PORT=3001 $0 start  # Start on custom port

EOF
            ;;
        *)
            log_error "Unknown command: ${command}"
            log_error "Run '$0 help' for usage information"
            exit 1
            ;;
    esac
}

main "$@"
